
[#-- 사용법:
       [= _pa_in_col (lst_map! ,'cd') ]
--]
[#function _pa_in lst_in]
[#assign str=""]
[#if lst_in!?is_enumerable]
	[#list lst_in! as x]
		[#assign str=str+"'"+x!?replace("'","''")+"'"]
		[#if x_has_next] [#assign str=str+" ,"][/#if]
	[/#list]
[#else]
	[#assign str="'"+lst_in!?replace("'","''")+"'"]
[/#if]
[#return str]
[/#function]

[#function _pa_in_col lst_in col]
[#assign str=""]
[#if lst_in!?is_enumerable]
	[#list lst_in! as x]
		[#assign str=str+"'"+x[col]!?replace("'","''")+"'"]
		[#if x_has_next] [#assign str=str+" ,"][/#if]
	[/#list]
[/#if]
[#return str]
[/#function]
